name: build

on: [push, pull_request]

env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"
  PHPUNIT_EXCLUDE_GROUP: db,wincache,xcache,zenddata

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            extensions: apcu, curl, dom, imagick, intl, mbstring, mcrypt, memcached
          - php: 8.3
            extensions: apcu, curl, dom, imagick, intl, mbstring, mcrypt, memcached

    steps:
      - name: Generate french locale.
        run: sudo locale-gen fr_FR.UTF-8

      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP.
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: ${{ matrix.extensions }}
          ini-values: apc.enabled=1,apc.shm_size=32M,apc.enable_cli=1, date.timezone='UTC', session.save_path="${{ runner.temp }}"
          php-version: ${{ matrix.php }}
          tools: pecl

      - name: Install Memcached.
        uses: niden/actions-memcached@v7

      - name: Install dependencies.
        run: composer install $DEFAULT_COMPOSER_FLAGS

      - name: Run tests with PHPUnit.
        run: vendor/bin/phpunit --verbose --exclude-group $PHPUNIT_EXCLUDE_GROUP --colors=always
