on:
  - pull_request
  - push

name: ci-mariadb

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: PHP ${{ matrix.php }}-mariadb-${{ matrix.mariadb }}
    env:
      extensions: curl, intl, pdo, pdo_mysql

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3]
        mariadb:
          - mariadb:10.4
          - mariadb:latest

    services:
      mysql:
        image: ${{ matrix.mariadb }}
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: yiitest
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          extensions: ${{ env.EXTENSIONS }}
          ini-values: date.timezone='UTC'
          php-version: ${{ matrix.php }}
          tools: composer:v2, pecl

      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run MariaDB tests with PHPUnit.
        run: vendor/bin/phpunit --group mysql --colors=always
